### ISSUE TITLE
TypeError: 'CSSNode' object is not callable running the tutorial sample code

### ISSUE THREAD

**Issue by elFua** [pybee/toga#70]
Running the code of the **slightly less toy example** from the tutorial at https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html causes the exception

`TypeError: 'CSSNode' object is not callable` 

at line 35 which happens to be:

``` python
    box.style(flex_direction='column', padding_top=10)
```

Removing all the styling related lines makes the program run fine and the GUI window to appear.
### Full stacktrace:

``` python
#$ python -m toga-temperature-converter
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/.virtualenvs/p3_toga_demo/projects/toga-my-test/toga-temperature-converter.py", line 52, in <module>
    app.main_loop()
  File "~/.virtualenvs/p3_toga_demo/lib/python3.5/site-packages/toga_cocoa/app.py", line 136, in main_loop
    self._startup()
  File "~/.virtualenvs/p3_toga_demo/lib/python3.5/site-packages/toga_cocoa/app.py", line 132, in _startup
    self.startup()
  File "~/.virtualenvs/p3_toga_demo/lib/python3.5/site-packages/toga/interface/app.py", line 59, in startup
    self.main_window.content = self._startup_method(self)
  File "~/.virtualenvs/p3_toga_demo/projects/toga-my-test/toga-temperature-converter.py", line 35, in build
    box.style(flex_direction='column', padding_top=10)
TypeError: 'CSSNode' object is not callable
```
### System Info

``` python
#$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G31

#$ python -V
Python 3.5.2

#$ pip freeze
appnope==0.1.0
colosseum==0.1.3
decorator==4.0.10
ipython==5.1.0
ipython-genutils==0.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.7
ptyprocess==0.5.1
Pygments==2.1.3
rubicon-objc==0.2.3
simplegeneric==0.8.1
six==1.10.0
toga==0.2.4
toga-cocoa==0.2.4
toga-core==0.2.4
toga-demo==0.2.4
traitlets==4.3.1
wcwidth==0.1.7
```

**Comment by pythoniac** [comment]
Same here on current Ubuntu Linux. Also the third example code will NOT run!

**Comment by freakboy3742** [comment]
Ok, this is weird. The example code was fixed 2 weeks ago, but RTD hasn't picked up the change. Investigating further.

**Comment by williamhatcher** [comment]
I'm still experiencing this same error on Python 3.6.0 on macOS. :(

**Comment by freakboy3742** [comment]
This should now be resolved through a major refactor of the style layer, plus some tweaks to the documentation.
